-- 删除sys_user表的外键约束
ALTER TABLE `sys_user` DROP FOREIGN KEY `fk_sys_department_users`;

-- 查看当前外键约束
SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'opshub' AND REFERENCED_TABLE_NAME IS NOT NULL;
