-- 添加GPU/NPU相关字段到hosts表
-- 日期: 2026-05-09
-- 描述: 为主机表添加GPU和NPU硬件信息字段，支持GPU/NPU设备的采集和统计

ALTER TABLE hosts ADD COLUMN IF NOT EXISTS gpu_info TEXT COMMENT 'GPU信息JSON';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS gpu_count INT DEFAULT 0 COMMENT 'GPU数量';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS gpu_model VARCHAR(200) COMMENT 'GPU型号';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS gpu_memory_total BIGINT DEFAULT 0 COMMENT 'GPU显存总量(字节)';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS npu_info TEXT COMMENT 'NPU信息JSON';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS npu_count INT DEFAULT 0 COMMENT 'NPU数量';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS npu_model VARCHAR(200) COMMENT 'NPU型号';
