// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: agent.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentHub_Connect_FullMethodName = "/agentproto.AgentHub/Connect"
)

// AgentHubClient is the client API for AgentHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentHubClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type agentHubClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentHubClient(cc grpc.ClientConnInterface) AgentHubClient {
	return &agentHubClient{cc}
}

func (c *agentHubClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentHub_ServiceDesc.Streams[0], AgentHub_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHub_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// AgentHubServer is the server API for AgentHub service.
// All implementations must embed UnimplementedAgentHubServer
// for forward compatibility.
type AgentHubServer interface {
	Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedAgentHubServer()
}

// UnimplementedAgentHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentHubServer struct{}

func (UnimplementedAgentHubServer) Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentHubServer) mustEmbedUnimplementedAgentHubServer() {}
func (UnimplementedAgentHubServer) testEmbeddedByValue()                  {}

// UnsafeAgentHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentHubServer will
// result in compilation errors.
type UnsafeAgentHubServer interface {
	mustEmbedUnimplementedAgentHubServer()
}

func RegisterAgentHubServer(s grpc.ServiceRegistrar, srv AgentHubServer) {
	// If the following call panics, it indicates UnimplementedAgentHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentHub_ServiceDesc, srv)
}

func _AgentHub_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentHubServer).Connect(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHub_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// AgentHub_ServiceDesc is the grpc.ServiceDesc for AgentHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentproto.AgentHub",
	HandlerType: (*AgentHubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentHub_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
