// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/agent.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent → Server
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_TermOutput
	//	*AgentMessage_FileChunk
	//	*AgentMessage_CmdResult
	//	*AgentMessage_FileList
	//	*AgentMessage_ProbeResult
	//	*AgentMessage_HttpProxyResponse
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTermOutput() *TerminalOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TermOutput); ok {
			return x.TermOutput
		}
	}
	return nil
}

func (x *AgentMessage) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *AgentMessage) GetCmdResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CmdResult); ok {
			return x.CmdResult
		}
	}
	return nil
}

func (x *AgentMessage) GetFileList() *FileListResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileList); ok {
			return x.FileList
		}
	}
	return nil
}

func (x *AgentMessage) GetProbeResult() *ProbeResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ProbeResult); ok {
			return x.ProbeResult
		}
	}
	return nil
}

func (x *AgentMessage) GetHttpProxyResponse() *HttpProxyResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HttpProxyResponse); ok {
			return x.HttpProxyResponse
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_TermOutput struct {
	TermOutput *TerminalOutput `protobuf:"bytes,3,opt,name=term_output,json=termOutput,proto3,oneof"`
}

type AgentMessage_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,4,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type AgentMessage_CmdResult struct {
	CmdResult *CommandResult `protobuf:"bytes,5,opt,name=cmd_result,json=cmdResult,proto3,oneof"`
}

type AgentMessage_FileList struct {
	FileList *FileListResult `protobuf:"bytes,6,opt,name=file_list,json=fileList,proto3,oneof"`
}

type AgentMessage_ProbeResult struct {
	ProbeResult *ProbeResult `protobuf:"bytes,7,opt,name=probe_result,json=probeResult,proto3,oneof"`
}

type AgentMessage_HttpProxyResponse struct {
	HttpProxyResponse *HttpProxyResponse `protobuf:"bytes,8,opt,name=http_proxy_response,json=httpProxyResponse,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_TermOutput) isAgentMessage_Payload() {}

func (*AgentMessage_FileChunk) isAgentMessage_Payload() {}

func (*AgentMessage_CmdResult) isAgentMessage_Payload() {}

func (*AgentMessage_FileList) isAgentMessage_Payload() {}

func (*AgentMessage_ProbeResult) isAgentMessage_Payload() {}

func (*AgentMessage_HttpProxyResponse) isAgentMessage_Payload() {}

// Server → Agent
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_HeartbeatAck
	//	*ServerMessage_TermOpen
	//	*ServerMessage_TermInput
	//	*ServerMessage_TermResize
	//	*ServerMessage_TermClose
	//	*ServerMessage_FileRequest
	//	*ServerMessage_CmdRequest
	//	*ServerMessage_ProbeRequest
	//	*ServerMessage_HttpProxyRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeatAck() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerMessage) GetTermOpen() *TerminalOpen {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TermOpen); ok {
			return x.TermOpen
		}
	}
	return nil
}

func (x *ServerMessage) GetTermInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TermInput); ok {
			return x.TermInput
		}
	}
	return nil
}

func (x *ServerMessage) GetTermResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TermResize); ok {
			return x.TermResize
		}
	}
	return nil
}

func (x *ServerMessage) GetTermClose() *TerminalClose {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TermClose); ok {
			return x.TermClose
		}
	}
	return nil
}

func (x *ServerMessage) GetFileRequest() *FileRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_FileRequest); ok {
			return x.FileRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetCmdRequest() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CmdRequest); ok {
			return x.CmdRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetProbeRequest() *ProbeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ProbeRequest); ok {
			return x.ProbeRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetHttpProxyRequest() *HttpProxyRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_HttpProxyRequest); ok {
			return x.HttpProxyRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterResponse `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatResponse `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerMessage_TermOpen struct {
	TermOpen *TerminalOpen `protobuf:"bytes,3,opt,name=term_open,json=termOpen,proto3,oneof"`
}

type ServerMessage_TermInput struct {
	TermInput *TerminalInput `protobuf:"bytes,4,opt,name=term_input,json=termInput,proto3,oneof"`
}

type ServerMessage_TermResize struct {
	TermResize *TerminalResize `protobuf:"bytes,5,opt,name=term_resize,json=termResize,proto3,oneof"`
}

type ServerMessage_TermClose struct {
	TermClose *TerminalClose `protobuf:"bytes,6,opt,name=term_close,json=termClose,proto3,oneof"`
}

type ServerMessage_FileRequest struct {
	FileRequest *FileRequest `protobuf:"bytes,7,opt,name=file_request,json=fileRequest,proto3,oneof"`
}

type ServerMessage_CmdRequest struct {
	CmdRequest *CommandRequest `protobuf:"bytes,8,opt,name=cmd_request,json=cmdRequest,proto3,oneof"`
}

type ServerMessage_ProbeRequest struct {
	ProbeRequest *ProbeRequest `protobuf:"bytes,9,opt,name=probe_request,json=probeRequest,proto3,oneof"`
}

type ServerMessage_HttpProxyRequest struct {
	HttpProxyRequest *HttpProxyRequest `protobuf:"bytes,10,opt,name=http_proxy_request,json=httpProxyRequest,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_HeartbeatAck) isServerMessage_Payload() {}

func (*ServerMessage_TermOpen) isServerMessage_Payload() {}

func (*ServerMessage_TermInput) isServerMessage_Payload() {}

func (*ServerMessage_TermResize) isServerMessage_Payload() {}

func (*ServerMessage_TermClose) isServerMessage_Payload() {}

func (*ServerMessage_FileRequest) isServerMessage_Payload() {}

func (*ServerMessage_CmdRequest) isServerMessage_Payload() {}

func (*ServerMessage_ProbeRequest) isServerMessage_Payload() {}

func (*ServerMessage_HttpProxyRequest) isServerMessage_Payload() {}

// ========== 注册 ==========
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Ips           []string               `protobuf:"bytes,6,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatInterval int32                  `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

// ========== 心跳 ==========
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ========== 终端 ==========
type TerminalOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOpen) Reset() {
	*x = TerminalOpen{}
	mi := &file_api_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpen) ProtoMessage() {}

func (x *TerminalOpen) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpen.ProtoReflect.Descriptor instead.
func (*TerminalOpen) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOpen) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalOpen) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_api_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_api_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *TerminalOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_api_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TerminalResize) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalClose) Reset() {
	*x = TerminalClose{}
	mi := &file_api_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalClose) ProtoMessage() {}

func (x *TerminalClose) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalClose.ProtoReflect.Descriptor instead.
func (*TerminalClose) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *TerminalClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ========== 文件操作 ==========
type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // list, upload, download, delete
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *FileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_api_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *FileChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *FileChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResult) Reset() {
	*x = FileListResult{}
	mi := &file_api_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResult) ProtoMessage() {}

func (x *FileListResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResult.ProtoReflect.Descriptor instead.
func (*FileListResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *FileListResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileListResult) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileListResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	IsDir         bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_api_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

// ========== 命令执行 ==========
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_api_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CommandResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ========== 拨测 ==========
type ProbeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProbeType string                 `protobuf:"bytes,2,opt,name=probe_type,json=probeType,proto3" json:"probe_type,omitempty"` // http, https, websocket, ping, tcp, udp
	Target    string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Port      int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Timeout   int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// HTTP/HTTPS/WebSocket specific
	Method              string            `protobuf:"bytes,10,opt,name=method,proto3" json:"method,omitempty"`
	Url                 string            `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Headers             map[string]string `protobuf:"bytes,12,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Params              map[string]string `protobuf:"bytes,13,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body                string            `protobuf:"bytes,14,opt,name=body,proto3" json:"body,omitempty"`
	ContentType         string            `protobuf:"bytes,15,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SkipVerify          bool              `protobuf:"varint,16,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	ProxyUrl            string            `protobuf:"bytes,17,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	Assertions          []*ProbeAssertion `protobuf:"bytes,18,rep,name=assertions,proto3" json:"assertions,omitempty"`
	MaxResponseBodySize int32             `protobuf:"varint,19,opt,name=max_response_body_size,json=maxResponseBodySize,proto3" json:"max_response_body_size,omitempty"` // 最大响应体大小(字节)，0表示不限制，默认4KB
	// WebSocket specific
	WsMessage     string `protobuf:"bytes,20,opt,name=ws_message,json=wsMessage,proto3" json:"ws_message,omitempty"`
	WsMessageType int32  `protobuf:"varint,21,opt,name=ws_message_type,json=wsMessageType,proto3" json:"ws_message_type,omitempty"` // 1=text, 2=binary
	WsReadTimeout int32  `protobuf:"varint,22,opt,name=ws_read_timeout,json=wsReadTimeout,proto3" json:"ws_read_timeout,omitempty"`
	// Ping specific
	Count         int32 `protobuf:"varint,30,opt,name=count,proto3" json:"count,omitempty"`
	PacketSize    int32 `protobuf:"varint,31,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ProbeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProbeRequest) GetProbeType() string {
	if x != nil {
		return x.ProbeType
	}
	return ""
}

func (x *ProbeRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProbeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProbeRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ProbeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProbeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProbeRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProbeRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProbeRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ProbeRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProbeRequest) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *ProbeRequest) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *ProbeRequest) GetAssertions() []*ProbeAssertion {
	if x != nil {
		return x.Assertions
	}
	return nil
}

func (x *ProbeRequest) GetMaxResponseBodySize() int32 {
	if x != nil {
		return x.MaxResponseBodySize
	}
	return 0
}

func (x *ProbeRequest) GetWsMessage() string {
	if x != nil {
		return x.WsMessage
	}
	return ""
}

func (x *ProbeRequest) GetWsMessageType() int32 {
	if x != nil {
		return x.WsMessageType
	}
	return 0
}

func (x *ProbeRequest) GetWsReadTimeout() int32 {
	if x != nil {
		return x.WsReadTimeout
	}
	return 0
}

func (x *ProbeRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ProbeRequest) GetPacketSize() int32 {
	if x != nil {
		return x.PacketSize
	}
	return 0
}

type ProbeAssertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // body, header, status
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"` // ==, >, >=, <, <=, contains, notcontains, regexp, notregexp
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeAssertion) Reset() {
	*x = ProbeAssertion{}
	mi := &file_api_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeAssertion) ProtoMessage() {}

func (x *ProbeAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeAssertion.ProtoReflect.Descriptor instead.
func (*ProbeAssertion) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ProbeAssertion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProbeAssertion) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProbeAssertion) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProbeAssertion) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *ProbeAssertion) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProbeResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Latency   float64                `protobuf:"fixed64,4,opt,name=latency,proto3" json:"latency,omitempty"` // ms
	// Network probe results
	PacketLoss      float64 `protobuf:"fixed64,10,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	PingRttAvg      float64 `protobuf:"fixed64,11,opt,name=ping_rtt_avg,json=pingRttAvg,proto3" json:"ping_rtt_avg,omitempty"`
	PingRttMin      float64 `protobuf:"fixed64,12,opt,name=ping_rtt_min,json=pingRttMin,proto3" json:"ping_rtt_min,omitempty"`
	PingRttMax      float64 `protobuf:"fixed64,13,opt,name=ping_rtt_max,json=pingRttMax,proto3" json:"ping_rtt_max,omitempty"`
	PingStddev      float64 `protobuf:"fixed64,14,opt,name=ping_stddev,json=pingStddev,proto3" json:"ping_stddev,omitempty"`
	PingPacketsSent int32   `protobuf:"varint,15,opt,name=ping_packets_sent,json=pingPacketsSent,proto3" json:"ping_packets_sent,omitempty"`
	PingPacketsRecv int32   `protobuf:"varint,16,opt,name=ping_packets_recv,json=pingPacketsRecv,proto3" json:"ping_packets_recv,omitempty"`
	TcpConnectTime  float64 `protobuf:"fixed64,17,opt,name=tcp_connect_time,json=tcpConnectTime,proto3" json:"tcp_connect_time,omitempty"`
	UdpWriteTime    float64 `protobuf:"fixed64,18,opt,name=udp_write_time,json=udpWriteTime,proto3" json:"udp_write_time,omitempty"`
	UdpReadTime     float64 `protobuf:"fixed64,19,opt,name=udp_read_time,json=udpReadTime,proto3" json:"udp_read_time,omitempty"`
	// HTTP/HTTPS/WebSocket results
	HttpStatusCode    int32             `protobuf:"varint,20,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	HttpResponseTime  float64           `protobuf:"fixed64,21,opt,name=http_response_time,json=httpResponseTime,proto3" json:"http_response_time,omitempty"`
	HttpContentLength int64             `protobuf:"varint,22,opt,name=http_content_length,json=httpContentLength,proto3" json:"http_content_length,omitempty"`
	ResponseBody      []byte            `protobuf:"bytes,23,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"` // 支持二进制内容（图片、CSS、JS等）
	ResponseHeaders   map[string]string `protobuf:"bytes,24,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Performance breakdown
	DnsLookupTime       float64 `protobuf:"fixed64,30,opt,name=dns_lookup_time,json=dnsLookupTime,proto3" json:"dns_lookup_time,omitempty"`
	TcpConnectTimeHttp  float64 `protobuf:"fixed64,31,opt,name=tcp_connect_time_http,json=tcpConnectTimeHttp,proto3" json:"tcp_connect_time_http,omitempty"`
	TlsHandshakeTime    float64 `protobuf:"fixed64,32,opt,name=tls_handshake_time,json=tlsHandshakeTime,proto3" json:"tls_handshake_time,omitempty"`
	Ttfb                float64 `protobuf:"fixed64,33,opt,name=ttfb,proto3" json:"ttfb,omitempty"` // time to first byte
	ContentTransferTime float64 `protobuf:"fixed64,34,opt,name=content_transfer_time,json=contentTransferTime,proto3" json:"content_transfer_time,omitempty"`
	// TLS/Certificate info
	TlsVersion      string `protobuf:"bytes,40,opt,name=tls_version,json=tlsVersion,proto3" json:"tls_version,omitempty"`
	TlsCipherSuite  string `protobuf:"bytes,41,opt,name=tls_cipher_suite,json=tlsCipherSuite,proto3" json:"tls_cipher_suite,omitempty"`
	SslCertNotAfter int64  `protobuf:"varint,42,opt,name=ssl_cert_not_after,json=sslCertNotAfter,proto3" json:"ssl_cert_not_after,omitempty"`
	// HTTP details
	RedirectCount       int32   `protobuf:"varint,50,opt,name=redirect_count,json=redirectCount,proto3" json:"redirect_count,omitempty"`
	RedirectTime        float64 `protobuf:"fixed64,51,opt,name=redirect_time,json=redirectTime,proto3" json:"redirect_time,omitempty"`
	FinalUrl            string  `protobuf:"bytes,52,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	ResponseHeaderBytes int32   `protobuf:"varint,53,opt,name=response_header_bytes,json=responseHeaderBytes,proto3" json:"response_header_bytes,omitempty"`
	ResponseBodyBytes   int32   `protobuf:"varint,54,opt,name=response_body_bytes,json=responseBodyBytes,proto3" json:"response_body_bytes,omitempty"`
	// Assertion results
	AssertionSuccess   bool                    `protobuf:"varint,60,opt,name=assertion_success,json=assertionSuccess,proto3" json:"assertion_success,omitempty"`
	AssertionResults   []*ProbeAssertionResult `protobuf:"bytes,61,rep,name=assertion_results,json=assertionResults,proto3" json:"assertion_results,omitempty"`
	AssertionPassCount int32                   `protobuf:"varint,62,opt,name=assertion_pass_count,json=assertionPassCount,proto3" json:"assertion_pass_count,omitempty"`
	AssertionFailCount int32                   `protobuf:"varint,63,opt,name=assertion_fail_count,json=assertionFailCount,proto3" json:"assertion_fail_count,omitempty"`
	AssertionEvalTime  float64                 `protobuf:"fixed64,64,opt,name=assertion_eval_time,json=assertionEvalTime,proto3" json:"assertion_eval_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_api_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ProbeResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProbeResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProbeResult) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *ProbeResult) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *ProbeResult) GetPingRttAvg() float64 {
	if x != nil {
		return x.PingRttAvg
	}
	return 0
}

func (x *ProbeResult) GetPingRttMin() float64 {
	if x != nil {
		return x.PingRttMin
	}
	return 0
}

func (x *ProbeResult) GetPingRttMax() float64 {
	if x != nil {
		return x.PingRttMax
	}
	return 0
}

func (x *ProbeResult) GetPingStddev() float64 {
	if x != nil {
		return x.PingStddev
	}
	return 0
}

func (x *ProbeResult) GetPingPacketsSent() int32 {
	if x != nil {
		return x.PingPacketsSent
	}
	return 0
}

func (x *ProbeResult) GetPingPacketsRecv() int32 {
	if x != nil {
		return x.PingPacketsRecv
	}
	return 0
}

func (x *ProbeResult) GetTcpConnectTime() float64 {
	if x != nil {
		return x.TcpConnectTime
	}
	return 0
}

func (x *ProbeResult) GetUdpWriteTime() float64 {
	if x != nil {
		return x.UdpWriteTime
	}
	return 0
}

func (x *ProbeResult) GetUdpReadTime() float64 {
	if x != nil {
		return x.UdpReadTime
	}
	return 0
}

func (x *ProbeResult) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

func (x *ProbeResult) GetHttpResponseTime() float64 {
	if x != nil {
		return x.HttpResponseTime
	}
	return 0
}

func (x *ProbeResult) GetHttpContentLength() int64 {
	if x != nil {
		return x.HttpContentLength
	}
	return 0
}

func (x *ProbeResult) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *ProbeResult) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *ProbeResult) GetDnsLookupTime() float64 {
	if x != nil {
		return x.DnsLookupTime
	}
	return 0
}

func (x *ProbeResult) GetTcpConnectTimeHttp() float64 {
	if x != nil {
		return x.TcpConnectTimeHttp
	}
	return 0
}

func (x *ProbeResult) GetTlsHandshakeTime() float64 {
	if x != nil {
		return x.TlsHandshakeTime
	}
	return 0
}

func (x *ProbeResult) GetTtfb() float64 {
	if x != nil {
		return x.Ttfb
	}
	return 0
}

func (x *ProbeResult) GetContentTransferTime() float64 {
	if x != nil {
		return x.ContentTransferTime
	}
	return 0
}

func (x *ProbeResult) GetTlsVersion() string {
	if x != nil {
		return x.TlsVersion
	}
	return ""
}

func (x *ProbeResult) GetTlsCipherSuite() string {
	if x != nil {
		return x.TlsCipherSuite
	}
	return ""
}

func (x *ProbeResult) GetSslCertNotAfter() int64 {
	if x != nil {
		return x.SslCertNotAfter
	}
	return 0
}

func (x *ProbeResult) GetRedirectCount() int32 {
	if x != nil {
		return x.RedirectCount
	}
	return 0
}

func (x *ProbeResult) GetRedirectTime() float64 {
	if x != nil {
		return x.RedirectTime
	}
	return 0
}

func (x *ProbeResult) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

func (x *ProbeResult) GetResponseHeaderBytes() int32 {
	if x != nil {
		return x.ResponseHeaderBytes
	}
	return 0
}

func (x *ProbeResult) GetResponseBodyBytes() int32 {
	if x != nil {
		return x.ResponseBodyBytes
	}
	return 0
}

func (x *ProbeResult) GetAssertionSuccess() bool {
	if x != nil {
		return x.AssertionSuccess
	}
	return false
}

func (x *ProbeResult) GetAssertionResults() []*ProbeAssertionResult {
	if x != nil {
		return x.AssertionResults
	}
	return nil
}

func (x *ProbeResult) GetAssertionPassCount() int32 {
	if x != nil {
		return x.AssertionPassCount
	}
	return 0
}

func (x *ProbeResult) GetAssertionFailCount() int32 {
	if x != nil {
		return x.AssertionFailCount
	}
	return 0
}

func (x *ProbeResult) GetAssertionEvalTime() float64 {
	if x != nil {
		return x.AssertionEvalTime
	}
	return 0
}

type ProbeAssertionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Actual        string                 `protobuf:"bytes,3,opt,name=actual,proto3" json:"actual,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeAssertionResult) Reset() {
	*x = ProbeAssertionResult{}
	mi := &file_api_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeAssertionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeAssertionResult) ProtoMessage() {}

func (x *ProbeAssertionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeAssertionResult.ProtoReflect.Descriptor instead.
func (*ProbeAssertionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ProbeAssertionResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProbeAssertionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProbeAssertionResult) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

func (x *ProbeAssertionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ========== HTTP 代理 ==========
type HttpProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Timeout       int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpProxyRequest) Reset() {
	*x = HttpProxyRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpProxyRequest) ProtoMessage() {}

func (x *HttpProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpProxyRequest.ProtoReflect.Descriptor instead.
func (*HttpProxyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *HttpProxyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpProxyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpProxyRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpProxyRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpProxyRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpProxyRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type HttpProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpProxyResponse) Reset() {
	*x = HttpProxyResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpProxyResponse) ProtoMessage() {}

func (x *HttpProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpProxyResponse.ProtoReflect.Descriptor instead.
func (*HttpProxyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *HttpProxyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpProxyResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpProxyResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpProxyResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpProxyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/agent.proto\x12\n" +
	"agentproto\"\x8f\x04\n" +
	"\fAgentMessage\x129\n" +
	"\bregister\x18\x01 \x01(\v2\x1b.agentproto.RegisterRequestH\x00R\bregister\x12<\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1c.agentproto.HeartbeatRequestH\x00R\theartbeat\x12=\n" +
	"\vterm_output\x18\x03 \x01(\v2\x1a.agentproto.TerminalOutputH\x00R\n" +
	"termOutput\x126\n" +
	"\n" +
	"file_chunk\x18\x04 \x01(\v2\x15.agentproto.FileChunkH\x00R\tfileChunk\x12:\n" +
	"\n" +
	"cmd_result\x18\x05 \x01(\v2\x19.agentproto.CommandResultH\x00R\tcmdResult\x129\n" +
	"\tfile_list\x18\x06 \x01(\v2\x1a.agentproto.FileListResultH\x00R\bfileList\x12<\n" +
	"\fprobe_result\x18\a \x01(\v2\x17.agentproto.ProbeResultH\x00R\vprobeResult\x12O\n" +
	"\x13http_proxy_response\x18\b \x01(\v2\x1d.agentproto.HttpProxyResponseH\x00R\x11httpProxyResponseB\t\n" +
	"\apayload\"\x9f\x05\n" +
	"\rServerMessage\x12A\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x1c.agentproto.RegisterResponseH\x00R\vregisterAck\x12D\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2\x1d.agentproto.HeartbeatResponseH\x00R\fheartbeatAck\x127\n" +
	"\tterm_open\x18\x03 \x01(\v2\x18.agentproto.TerminalOpenH\x00R\btermOpen\x12:\n" +
	"\n" +
	"term_input\x18\x04 \x01(\v2\x19.agentproto.TerminalInputH\x00R\ttermInput\x12=\n" +
	"\vterm_resize\x18\x05 \x01(\v2\x1a.agentproto.TerminalResizeH\x00R\n" +
	"termResize\x12:\n" +
	"\n" +
	"term_close\x18\x06 \x01(\v2\x19.agentproto.TerminalCloseH\x00R\ttermClose\x12<\n" +
	"\ffile_request\x18\a \x01(\v2\x17.agentproto.FileRequestH\x00R\vfileRequest\x12=\n" +
	"\vcmd_request\x18\b \x01(\v2\x1a.agentproto.CommandRequestH\x00R\n" +
	"cmdRequest\x12?\n" +
	"\rprobe_request\x18\t \x01(\v2\x18.agentproto.ProbeRequestH\x00R\fprobeRequest\x12L\n" +
	"\x12http_proxy_request\x18\n" +
	" \x01(\v2\x1c.agentproto.HttpProxyRequestH\x00R\x10httpProxyRequestB\t\n" +
	"\apayload\"\x98\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x10\n" +
	"\x03ips\x18\x06 \x03(\tR\x03ips\"u\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\x05R\x11heartbeatInterval\"\xb3\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x04 \x01(\x01R\tdiskUsage\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\fTerminalOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"B\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"C\n" +
	"\x0eTerminalOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"W\n" +
	"\x0eTerminalResize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\".\n" +
	"\rTerminalClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x88\x01\n" +
	"\vFileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\"f\n" +
	"\tFileChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"q\n" +
	"\x0eFileListResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\x05files\x18\x02 \x03(\v2\x14.agentproto.FileInfoR\x05files\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"x\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x19\n" +
	"\bmod_time\x18\x04 \x01(\x03R\amodTime\x12\x15\n" +
	"\x06is_dir\x18\x05 \x01(\bR\x05isDir\"c\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"\x91\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xbe\x06\n" +
	"\fProbeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"probe_type\x18\x02 \x01(\tR\tprobeType\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x12\x16\n" +
	"\x06method\x18\n" +
	" \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\v \x01(\tR\x03url\x12?\n" +
	"\aheaders\x18\f \x03(\v2%.agentproto.ProbeRequest.HeadersEntryR\aheaders\x12<\n" +
	"\x06params\x18\r \x03(\v2$.agentproto.ProbeRequest.ParamsEntryR\x06params\x12\x12\n" +
	"\x04body\x18\x0e \x01(\tR\x04body\x12!\n" +
	"\fcontent_type\x18\x0f \x01(\tR\vcontentType\x12\x1f\n" +
	"\vskip_verify\x18\x10 \x01(\bR\n" +
	"skipVerify\x12\x1b\n" +
	"\tproxy_url\x18\x11 \x01(\tR\bproxyUrl\x12:\n" +
	"\n" +
	"assertions\x18\x12 \x03(\v2\x1a.agentproto.ProbeAssertionR\n" +
	"assertions\x123\n" +
	"\x16max_response_body_size\x18\x13 \x01(\x05R\x13maxResponseBodySize\x12\x1d\n" +
	"\n" +
	"ws_message\x18\x14 \x01(\tR\twsMessage\x12&\n" +
	"\x0fws_message_type\x18\x15 \x01(\x05R\rwsMessageType\x12&\n" +
	"\x0fws_read_timeout\x18\x16 \x01(\x05R\rwsReadTimeout\x12\x14\n" +
	"\x05count\x18\x1e \x01(\x05R\x05count\x12\x1f\n" +
	"\vpacket_size\x18\x1f \x01(\x05R\n" +
	"packetSize\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x0eProbeAssertion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"\xda\f\n" +
	"\vProbeResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\alatency\x18\x04 \x01(\x01R\alatency\x12\x1f\n" +
	"\vpacket_loss\x18\n" +
	" \x01(\x01R\n" +
	"packetLoss\x12 \n" +
	"\fping_rtt_avg\x18\v \x01(\x01R\n" +
	"pingRttAvg\x12 \n" +
	"\fping_rtt_min\x18\f \x01(\x01R\n" +
	"pingRttMin\x12 \n" +
	"\fping_rtt_max\x18\r \x01(\x01R\n" +
	"pingRttMax\x12\x1f\n" +
	"\vping_stddev\x18\x0e \x01(\x01R\n" +
	"pingStddev\x12*\n" +
	"\x11ping_packets_sent\x18\x0f \x01(\x05R\x0fpingPacketsSent\x12*\n" +
	"\x11ping_packets_recv\x18\x10 \x01(\x05R\x0fpingPacketsRecv\x12(\n" +
	"\x10tcp_connect_time\x18\x11 \x01(\x01R\x0etcpConnectTime\x12$\n" +
	"\x0eudp_write_time\x18\x12 \x01(\x01R\fudpWriteTime\x12\"\n" +
	"\rudp_read_time\x18\x13 \x01(\x01R\vudpReadTime\x12(\n" +
	"\x10http_status_code\x18\x14 \x01(\x05R\x0ehttpStatusCode\x12,\n" +
	"\x12http_response_time\x18\x15 \x01(\x01R\x10httpResponseTime\x12.\n" +
	"\x13http_content_length\x18\x16 \x01(\x03R\x11httpContentLength\x12#\n" +
	"\rresponse_body\x18\x17 \x01(\fR\fresponseBody\x12W\n" +
	"\x10response_headers\x18\x18 \x03(\v2,.agentproto.ProbeResult.ResponseHeadersEntryR\x0fresponseHeaders\x12&\n" +
	"\x0fdns_lookup_time\x18\x1e \x01(\x01R\rdnsLookupTime\x121\n" +
	"\x15tcp_connect_time_http\x18\x1f \x01(\x01R\x12tcpConnectTimeHttp\x12,\n" +
	"\x12tls_handshake_time\x18  \x01(\x01R\x10tlsHandshakeTime\x12\x12\n" +
	"\x04ttfb\x18! \x01(\x01R\x04ttfb\x122\n" +
	"\x15content_transfer_time\x18\" \x01(\x01R\x13contentTransferTime\x12\x1f\n" +
	"\vtls_version\x18( \x01(\tR\n" +
	"tlsVersion\x12(\n" +
	"\x10tls_cipher_suite\x18) \x01(\tR\x0etlsCipherSuite\x12+\n" +
	"\x12ssl_cert_not_after\x18* \x01(\x03R\x0fsslCertNotAfter\x12%\n" +
	"\x0eredirect_count\x182 \x01(\x05R\rredirectCount\x12#\n" +
	"\rredirect_time\x183 \x01(\x01R\fredirectTime\x12\x1b\n" +
	"\tfinal_url\x184 \x01(\tR\bfinalUrl\x122\n" +
	"\x15response_header_bytes\x185 \x01(\x05R\x13responseHeaderBytes\x12.\n" +
	"\x13response_body_bytes\x186 \x01(\x05R\x11responseBodyBytes\x12+\n" +
	"\x11assertion_success\x18< \x01(\bR\x10assertionSuccess\x12M\n" +
	"\x11assertion_results\x18= \x03(\v2 .agentproto.ProbeAssertionResultR\x10assertionResults\x120\n" +
	"\x14assertion_pass_count\x18> \x01(\x05R\x12assertionPassCount\x120\n" +
	"\x14assertion_fail_count\x18? \x01(\x05R\x12assertionFailCount\x12.\n" +
	"\x13assertion_eval_time\x18@ \x01(\x01R\x11assertionEvalTime\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x14ProbeAssertionResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06actual\x18\x03 \x01(\tR\x06actual\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8a\x02\n" +
	"\x10HttpProxyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12C\n" +
	"\aheaders\x18\x04 \x03(\v2).agentproto.HttpProxyRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\x11HttpProxyResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12D\n" +
	"\aheaders\x18\x03 \x03(\v2*.agentproto.HttpProxyResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012N\n" +
	"\bAgentHub\x12B\n" +
	"\aConnect\x12\x18.agentproto.AgentMessage\x1a\x19.agentproto.ServerMessage(\x010\x01B-Z+github.com/ydcloud-dy/opshub/pkg/agentprotob\x06proto3"

var (
	file_api_proto_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_proto_rawDescData []byte
)

func file_api_proto_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_proto_rawDescData
}

var file_api_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_proto_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),         // 0: agentproto.AgentMessage
	(*ServerMessage)(nil),        // 1: agentproto.ServerMessage
	(*RegisterRequest)(nil),      // 2: agentproto.RegisterRequest
	(*RegisterResponse)(nil),     // 3: agentproto.RegisterResponse
	(*HeartbeatRequest)(nil),     // 4: agentproto.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 5: agentproto.HeartbeatResponse
	(*TerminalOpen)(nil),         // 6: agentproto.TerminalOpen
	(*TerminalInput)(nil),        // 7: agentproto.TerminalInput
	(*TerminalOutput)(nil),       // 8: agentproto.TerminalOutput
	(*TerminalResize)(nil),       // 9: agentproto.TerminalResize
	(*TerminalClose)(nil),        // 10: agentproto.TerminalClose
	(*FileRequest)(nil),          // 11: agentproto.FileRequest
	(*FileChunk)(nil),            // 12: agentproto.FileChunk
	(*FileListResult)(nil),       // 13: agentproto.FileListResult
	(*FileInfo)(nil),             // 14: agentproto.FileInfo
	(*CommandRequest)(nil),       // 15: agentproto.CommandRequest
	(*CommandResult)(nil),        // 16: agentproto.CommandResult
	(*ProbeRequest)(nil),         // 17: agentproto.ProbeRequest
	(*ProbeAssertion)(nil),       // 18: agentproto.ProbeAssertion
	(*ProbeResult)(nil),          // 19: agentproto.ProbeResult
	(*ProbeAssertionResult)(nil), // 20: agentproto.ProbeAssertionResult
	(*HttpProxyRequest)(nil),     // 21: agentproto.HttpProxyRequest
	(*HttpProxyResponse)(nil),    // 22: agentproto.HttpProxyResponse
	nil,                          // 23: agentproto.ProbeRequest.HeadersEntry
	nil,                          // 24: agentproto.ProbeRequest.ParamsEntry
	nil,                          // 25: agentproto.ProbeResult.ResponseHeadersEntry
	nil,                          // 26: agentproto.HttpProxyRequest.HeadersEntry
	nil,                          // 27: agentproto.HttpProxyResponse.HeadersEntry
}
var file_api_proto_agent_proto_depIdxs = []int32{
	2,  // 0: agentproto.AgentMessage.register:type_name -> agentproto.RegisterRequest
	4,  // 1: agentproto.AgentMessage.heartbeat:type_name -> agentproto.HeartbeatRequest
	8,  // 2: agentproto.AgentMessage.term_output:type_name -> agentproto.TerminalOutput
	12, // 3: agentproto.AgentMessage.file_chunk:type_name -> agentproto.FileChunk
	16, // 4: agentproto.AgentMessage.cmd_result:type_name -> agentproto.CommandResult
	13, // 5: agentproto.AgentMessage.file_list:type_name -> agentproto.FileListResult
	19, // 6: agentproto.AgentMessage.probe_result:type_name -> agentproto.ProbeResult
	22, // 7: agentproto.AgentMessage.http_proxy_response:type_name -> agentproto.HttpProxyResponse
	3,  // 8: agentproto.ServerMessage.register_ack:type_name -> agentproto.RegisterResponse
	5,  // 9: agentproto.ServerMessage.heartbeat_ack:type_name -> agentproto.HeartbeatResponse
	6,  // 10: agentproto.ServerMessage.term_open:type_name -> agentproto.TerminalOpen
	7,  // 11: agentproto.ServerMessage.term_input:type_name -> agentproto.TerminalInput
	9,  // 12: agentproto.ServerMessage.term_resize:type_name -> agentproto.TerminalResize
	10, // 13: agentproto.ServerMessage.term_close:type_name -> agentproto.TerminalClose
	11, // 14: agentproto.ServerMessage.file_request:type_name -> agentproto.FileRequest
	15, // 15: agentproto.ServerMessage.cmd_request:type_name -> agentproto.CommandRequest
	17, // 16: agentproto.ServerMessage.probe_request:type_name -> agentproto.ProbeRequest
	21, // 17: agentproto.ServerMessage.http_proxy_request:type_name -> agentproto.HttpProxyRequest
	14, // 18: agentproto.FileListResult.files:type_name -> agentproto.FileInfo
	23, // 19: agentproto.ProbeRequest.headers:type_name -> agentproto.ProbeRequest.HeadersEntry
	24, // 20: agentproto.ProbeRequest.params:type_name -> agentproto.ProbeRequest.ParamsEntry
	18, // 21: agentproto.ProbeRequest.assertions:type_name -> agentproto.ProbeAssertion
	25, // 22: agentproto.ProbeResult.response_headers:type_name -> agentproto.ProbeResult.ResponseHeadersEntry
	20, // 23: agentproto.ProbeResult.assertion_results:type_name -> agentproto.ProbeAssertionResult
	26, // 24: agentproto.HttpProxyRequest.headers:type_name -> agentproto.HttpProxyRequest.HeadersEntry
	27, // 25: agentproto.HttpProxyResponse.headers:type_name -> agentproto.HttpProxyResponse.HeadersEntry
	0,  // 26: agentproto.AgentHub.Connect:input_type -> agentproto.AgentMessage
	1,  // 27: agentproto.AgentHub.Connect:output_type -> agentproto.ServerMessage
	27, // [27:28] is the sub-list for method output_type
	26, // [26:27] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_api_proto_agent_proto_init() }
func file_api_proto_agent_proto_init() {
	if File_api_proto_agent_proto != nil {
		return
	}
	file_api_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_TermOutput)(nil),
		(*AgentMessage_FileChunk)(nil),
		(*AgentMessage_CmdResult)(nil),
		(*AgentMessage_FileList)(nil),
		(*AgentMessage_ProbeResult)(nil),
		(*AgentMessage_HttpProxyResponse)(nil),
	}
	file_api_proto_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_HeartbeatAck)(nil),
		(*ServerMessage_TermOpen)(nil),
		(*ServerMessage_TermInput)(nil),
		(*ServerMessage_TermResize)(nil),
		(*ServerMessage_TermClose)(nil),
		(*ServerMessage_FileRequest)(nil),
		(*ServerMessage_CmdRequest)(nil),
		(*ServerMessage_ProbeRequest)(nil),
		(*ServerMessage_HttpProxyRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_proto = out.File
	file_api_proto_agent_proto_goTypes = nil
	file_api_proto_agent_proto_depIdxs = nil
}
